export const PRODUTO_LABELS = {
  pageTitle: "Produtos",
  pageSubtitle:
    "Linhas de software Softcom e suas versões, módulos e rotinas de liberação",
  novo: "Novo produto",
  voltar: "Voltar",
  filtros: "Filtros",
  nome: "Nome do produto",
  nomePlaceholder: "Buscar por nome…",
  setor: "Setor",
  listagem: "Listagem de produtos",
  registro: "Registro",
  nomeColuna: "Nome",
  po: "PO",
  scrumMaster: "Scrum Master",
  data: "Data",
  status: "Status",
  ativo: "Ativo",
  desativado: "Desativado",
  vacaLeiteira: "Vaca leiteira",
  limparFiltros: "Limpar filtros",
  tentarNovamente: "Tentar novamente",
  semFiltroTitulo: "Nenhum filtro aplicado",
  semFiltroDescricao:
    "Informe o nome ou o setor para pesquisar os produtos.",
  vazioTitulo: "Nenhum produto cadastrado",
  vazioDescricao:
    "Cadastre a primeira linha de software para começar a registrar versões e liberações.",
  vazioFiltroTitulo: "Nenhum produto encontrado para esses filtros",
  vazioFiltroDescricao: "Ajuste o nome ou o setor para ampliar a busca.",
  erroTitulo: "Não foi possível carregar",
  erroDescricao:
    "A lista de produtos não respondeu. Tente novamente em alguns instantes.",
  cadastroTitulo: "Novo produto",
  cadastroSubtitle: "Cadastre uma linha de software Softcom",
  identificacao: "Identificação",
  responsaveis: "Responsáveis",
  informacoesTecnicas: "Informações técnicas",
  opcional: "Opcional",
  exibicaoControle: "Exibição e controle",
  exibicaoHint: "O produto nasce ativo; estas chaves podem mudar depois.",
  productOwner: "Product Owner",
  vinculadoA: "Vinculado a",
  vinculadoPlaceholder: "Nenhum",
  necessidadeComercial: "Necessidade comercial",
  necessidadePlaceholder: "ID",
  necessidadeHint: "Opcional — ID da necessidade no comercial",
  responsavelSuporte: "Responsável suporte",
  responsavelParametrizacao: "Responsável parametrização",
  responsavelBugs: "Responsável bugs (suporte)",
  responsavelMelhorias: "Responsável melhorias (suporte)",
  mostrarConsulta: "Mostrar na consulta",
  mostrarConsultaHint: "Aparece nas seleções de produto do Softflow",
  mostrarTeste: "Mostrar em teste",
  mostrarTesteHint: "Disponível nos ambientes de teste",
  faqExibir: "Exibir FAQ",
  faqExibirHint: "Mostra a base de perguntas na documentação",
  calcularBurndown: "Calcular burndown",
  calcularBurndownHint: "Entra no gráfico de progresso das versões",
  vacaLeiteiraHint: "Produto maduro, em manutenção",
  tecnicasPlaceholder: "Stack, dependências, particularidades de instalação…",
  nomePlaceholderCadastro: "Ex.: Smart Express",
  cancelar: "Cancelar",
  criarProduto: "Criar produto",
  criando: "Criando…",
  footerNovoHint: "Registro e data do cadastro são gerados ao salvar",
  reviseObrigatorios: "Revise os campos obrigatórios",
  criadoSucesso: "Produto criado",
  erroCriar: "Erro ao criar produto.",
  poPlaceholder: "Selecione o Product Owner...",
  smPlaceholder: "Selecione o Scrum Master...",
  colaboradorNenhum: "Nenhum",
  dataCadastro: "Data do cadastro",
  geradosServidor: "Gerados pelo servidor",
  abaDados: "Dados gerais",
  abaVersoes: "Versões",
  abaModulos: "Módulos",
  abaChecklist: "Checklist",
  abaScripts: "Scripts",
  resumo: "Resumo",
  acoes: "Ações",
  somenteLeitura: "Somente leitura",
  salvarAlteracoes: "Salvar alterações",
  salvando: "Salvando…",
  descartar: "Descartar",
  alteracoesNaoSalvas: "Alterações não salvas",
  desativarProduto: "Desativar produto",
  reativarProduto: "Reativar produto",
  desativarAjuda:
    "Produtos desativados somem das seleções, mas o histórico é mantido.",
  reativarAjuda: "Reativar volta a exibir o produto nas seleções.",
  desativarTitulo: "Desativar produto?",
  reativarTitulo: "Reativar produto?",
  desativarDescricao:
    "O produto deixa de aparecer nas seleções. O histórico é mantido.",
  reativarDescricao: "O produto volta a aparecer nas seleções do Softflow.",
  sim: "Sim",
  nao: "Não",
  continuarEditando: "Continuar editando",
  descartarTitulo: "Descartar alterações?",
  descartarDescricao:
    "As alterações feitas em Dados gerais não foram salvas e serão perdidas.",
  atualizadoSucesso: "Alterações salvas",
  erroAtualizar: "Erro ao atualizar produto.",
  erroCarregarDetalhe: "Não foi possível carregar o produto.",
  produtoIndisponivel: "Dados do produto indisponíveis.",
  naoEncontradoTitulo: "Produto não encontrado",
  naoEncontradoDescricao:
    "O produto que você está tentando acessar não existe, foi excluído ou você não tem permissão para visualizá-lo.",
  voltarListagem: "Voltar para listagem",
  abaEmConstrucaoTitulo: "Em construção",
  abaVersoesDescricao:
    "O cadastro de versões deste produto entra na próxima etapa.",
  novaVersao: "Nova versão",
  novaVersaoTitulo: "Nova versão",
  editarVersaoTitulo: "Editar versão",
  versaoColuna: "Versão",
  versaoPlaceholder: "0.0.0.0",
  versaoFormato: "Use apenas números e pontos, como 8.1.1.0",
  statusAberto: "ABERTO",
  statusFechado: "FECHADO",
  dataAbertura: "Data de abertura",
  dataFechamento: "Data de fechamento",
  previsaoFechamento: "Previsão de fechamento",
  notasVersao: "Notas da versão",
  notasPlaceholder: "O que entra nesta versão…",
  helptools: "Hotfix",
  estacionamentoIdeias: "Estacionamento de ideias",
  testador: "Testador",
  dataVersao: "Data da versão",
  sequencia: "Sequência",
  editar: "Editar",
  excluir: "Excluir",
  salvar: "Salvar",
  acoesMenu: "Ações",
  fecharVersao: "Fechar versão",
  reabrirVersao: "Reabrir versão",
  reabrir: "Reabrir",
  entendi: "Entendi",
  versaoSalva: "Versão salva",
  versaoFechada: "Versão fechada",
  versaoReaberta: "Versão reaberta",
  versaoExcluida: "Versão excluída",
  versoesVazioTitulo: "Nenhuma versão cadastrada",
  versoesVazioDescricao:
    "As versões organizam casos e liberações deste produto.",
  erroCarregarVersoes: "Não foi possível carregar as versões.",
  fecharVersaoDescricao:
    "A versão deixa de receber casos novos. Informe a data de fechamento.",
  reabrirVersaoDescricao:
    "A versão volta a aceitar casos e liberações.",
  excluirVersaoTitulo: "Excluir versão",
  excluirVersaoDescricao: "Esta ação não pode ser desfeita.",
  excluirVersaoAviso:
    "Casos e liberações podem estar vinculados a esta versão.",
  conflitoVersaoTitulo: "Não é possível excluir",
  conflitoVersaoDescricao:
    "Esta versão está em uso e não pode ser excluída. Feche-a em vez disso.",
  conflitoVersaoAviso:
    "Há casos e liberações vinculados a esta versão.",
  semPrevisao: "Sem previsão",
  previsaoPrefix: "Previsão",
  fechadaEm: "Fechada em",
  reviseDestacados: "Revise os campos destacados",
  erroSalvarVersao: "Erro ao salvar versão.",
  erroExcluirVersao: "Erro ao excluir versão.",
  dataFechamentoObrigatoria: "Informe a data de fechamento",
  fechamentoAnteriorAbertura:
    "Não pode ser anterior à data de abertura",
  novoModulo: "Novo módulo",
  novoModuloTitulo: "Novo módulo",
  editarModuloTitulo: "Editar módulo",
  nomeModulo: "Nome do módulo",
  nomeModuloPlaceholder: "SMART PDV",
  nomeModuloHint: "Use caixa alta, como os módulos existentes",
  ordemImpressao: "Ordem de impressão",
  versionado: "Versionado",
  atualizador: "Atualizador",
  impressao: "Impressão",
  semOrdem: "Sem ordem",
  moduloSalvo: "Módulo salvo",
  moduloExcluido: "Módulo excluído",
  modulosVazioTitulo: "Nenhum módulo cadastrado",
  modulosVazioDescricao:
    "Módulos definem o que é versionado e atualizado na liberação.",
  erroCarregarModulos: "Não foi possível carregar os módulos.",
  excluirModuloTitulo: "Excluir módulo",
  excluirModuloDescricao:
    "O módulo deixa de ser oferecido nas liberações deste produto.",
  conflitoModuloTitulo: "Não é possível excluir",
  conflitoModuloDescricao:
    "Este módulo está em uso e não pode ser excluído.",
  erroSalvarModulo: "Erro ao salvar módulo.",
  erroExcluirModulo: "Erro ao excluir módulo.",
  informeNomeModulo: "Informe o nome do módulo",
  ordemInvalida: "Informe um número inteiro",
  abaModulosDescricao:
    "O cadastro de módulos deste produto entra na próxima etapa.",
  checklistSubtitulo: "Rotina executada na liberação deste produto",
  checklistVazioTitulo: "Nenhum item no checklist",
  checklistVazioDescricao:
    "Adicione os passos da rotina de liberação abaixo.",
  erroCarregarChecklist: "Não foi possível carregar o checklist.",
  novoItemPlaceholder: "Novo item…",
  adicionar: "Adicionar",
  descrevaItemChecklist: "Descreva o item do checklist",
  descrevaItemAntesAdicionar: "Descreva o item antes de adicionar",
  itemAtualizado: "Item atualizado",
  itemAdicionado: "Item adicionado ao checklist",
  itemExcluido: "Item excluído",
  excluirItemChecklistTitulo: "Excluir item do checklist?",
  erroSalvarChecklist: "Erro ao salvar item do checklist.",
  erroExcluirChecklist: "Erro ao excluir item do checklist.",
  conflitoChecklistTitulo: "Não é possível excluir",
  conflitoChecklistDescricao:
    "Este item está em uso e não pode ser excluído.",
  responsavel: "Responsável",
  abaChecklistDescricao:
    "O checklist de liberação deste produto entra na próxima etapa.",
  novoScript: "Novo script",
  novoScriptTitulo: "Novo script",
  editarScriptTitulo: "Editar script",
  scriptTitulo: "Título",
  scriptTituloPlaceholder: "Como levantar o ambiente de teste",
  scriptOrdem: "Ordem",
  procedimento: "Procedimento",
  procedimentoPlaceholder:
    "Um passo por linha. Nunca inclua senhas ou endereços internos.",
  informeTituloScript: "Informe o título",
  informeProcedimento: "Informe o procedimento",
  scriptSalvo: "Script salvo",
  scriptExcluido: "Script excluído",
  scriptsVazioTitulo: "Nenhum script cadastrado",
  scriptsVazioDescricao:
    "Registre os procedimentos de ambiente e testes deste produto.",
  erroCarregarScripts: "Não foi possível carregar os scripts.",
  excluirScriptTitulo: "Excluir script?",
  excluirScriptAviso:
    "O procedimento será removido da documentação deste produto.",
  erroSalvarScript: "Erro ao salvar script.",
  erroExcluirScript: "Erro ao excluir script.",
  conflitoScriptTitulo: "Não é possível excluir",
  conflitoScriptDescricao:
    "Este script está em uso e não pode ser excluído.",
  copiar: "Copiar",
  copiado: "Copiado",
  erroCopiar: "Não foi possível copiar o script.",
  abaScriptsDescricao:
    "Os scripts deste produto entram na próxima etapa.",
} as const;

export const PRODUTOS_PAGE_SIZE = 15;
